### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Alexey55** [ter-haar/galaxyconquest#25]
RUS: Корабли первого игрока (зелёные) не стреляют. Ездить ездят, но не стреляют.
ENG: First player's (green) ships are not shooting. Moving, but not shooting. (для нашей англоязычной аудитории)

**Comment by DmitryTyunkov** [comment]
Как было решено на паре изначально корабли не оборудованы оружием, чтобы появилось вооружение его надо изучить.

**Comment by Alexey55** [comment]
А, вот оно что. Понял
